d;c;;my_project
d;c;my_project;setings
f;c;my_project\setings;__init__.py
f;c;my_project\setings;dev.py
f;c;my_project\setings;prod.py
d;c;my_project;mainapp
f;c;my_project\mainapp;__init__.py
f;c;my_project\mainapp;models.py
f;c;my_project\mainapp;views.py
d;c;my_project\mainapp;templates
d;c;my_project\mainapp\templates;mainapp
f;c;my_project\mainapp\templates\mainapp;base.html
f;c;my_project\mainapp\templates\mainapp;index.html
d;c;my_project;authapp
f;c;my_project\authapp;__init__.py
f;c;my_project\authapp;models.py
f;c;my_project\authapp;views.py
d;c;my_project\authapp;templates
d;c;my_project\authapp\templates;authapp
f;c;my_project\authapp\templates\authapp;base.html
f;c;my_project\authapp\templates\authapp;index.html
